### ISSUE TITLE
error when mounting macOS-image (Mojave)

### ISSUE THREAD

**Issue by Banaanhangwagen** [sgan81/apfs-fuse#74] opened 2019-01-02 11:03 UTC
apfs-fuse does not work any more while mounting macOS-image with Mojave (10.14); (mounting a mac-OS image with High Sierra (10.13) works flawless)

apfs-fuse gives the following error:
`This doesn't seem to be an apfs volume (invalid superblock). Unable to get Volume`
apfs-quick-dump gives a  `segmentation fault` error.

Maybe Apple did some changes and a little re-calibration needs to be done?

I have to precise that this only the case for macOS images; when mounting images of USB thumb-drives (apfs) created on Mojave, it works without any problems

**Comment by muellermartin** [comment] 2019-02-04 17:18
My guess would be, that the macOS images are encrypted while the ones on the USB thumb drives are not and therefore work. Did you try passing the encryption key?

**Comment by Banaanhangwagen** [comment] 2019-02-05 19:36
Yes I did.
I confirm that the USB thumb drives that I created were - ofcourse - also encrypted.

**Comment by sgan81** [comment] 2019-02-06 23:03
And 'diskutil list' confirms that this is an APFS volume?

**Comment by sgan81** [comment] 2019-02-07 00:45
Other question ... what do you mean by macOS image? Was it created from some internal drive, and if yes, what mac is it?

**Comment by Banaanhangwagen** [comment] 2019-02-08 08:22
> 
> 
> And 'diskutil list' confirms that this is an APFS volume?

Yes.

> 
> Other question ... what do you mean by macOS image? Was it created from some internal drive, and if yes, what mac is it?

An image (raw) of disk0 of a macbook pro (A1707)

**Comment by sgan81** [comment] 2019-02-21 20:45
Is there any more info when running apfs-fuse with -d 255?
I don't know if the MacBook Pro A1707 contains the T2 chip, but if it does, the internal APFS volume is always encrypted in a way I haven't yet figured out, and is probably quite hard to figure out ...

**Comment by Banaanhangwagen** [comment] 2019-02-26 13:15
> 
> 
> Is there any more info when running apfs-fuse with -d 255?

No. It says _invalid superblock_.

> I don't know if the MacBook Pro A1707 contains the T2 chip,[...]

This model does not contain the T2 chip.

For what it's worth: when mounting the image on a macOS, I have to precise _-blocksize 4096_ explicitly, otherwise it won't work.
`hdiutil attach –blocksize 4096 /path_to/apfs.dmg`

**Comment by sgan81** [comment] 2019-02-26 13:31
Hmmm, if it says that the superblock is invalid, then there is something wrong. Because the superblock should be present even on encrypted devices.

The apfs-dump-quick utility should work now, I fixed the segfault yesterday.

**Comment by Banaanhangwagen** [comment] 2019-02-27 13:36
> 
> The apfs-dump-quick utility should work now, I fixed the segfault yesterday.

You fixed it: no more segfault...but I get now the following error: 
`This doesn't seem to be an apfs volume (invalid superblock)
Unable to init container`

**Comment by V0oDoo** [comment] 2019-03-08 06:46
Same problem here, running Kali Linux on a macbook air with mojave. Trying to mount the internal harddrive which is encrypted but it doesn't prompt for decryption credentials.

"This doesn't seem to be an apfs volume (invalid superblock). Unable to get Volume"

**Comment by sgan81** [comment] 2019-03-09 20:11
The error message means that the superblock doesn't contain the 'NXSB' magic string when it should. Maybe it is related to the 4K block size. You seem to use an image containing several partitions. Maybe I did something wrong there ... let me check and get back to you later.

**Comment by sgan81** [comment] 2019-03-09 20:12
Actually, now that there is an ```apfsutil``` ... can you run that one on your image and provide me with it's output, so I can have a look at the partition table? Thanks.

**Comment by sgan81** [comment] 2019-03-09 20:26
Found a bug in the partition table handling code that might be the reason for your troubles. Please try again using the newest commit.

**Comment by V0oDoo** [comment] 2019-03-09 21:38
> 
> 
> Found a bug in the partition table handling code that might be the reason for your troubles. Please try again using the newest commit.

Sorry, no change. 
I'm not using a image (trying to mount the internal HDD). I run the ./apfsutil /dev/sda2 and it says the same "This doesnt seem to be an apfs volume (invalid superblock).
Unable to open APFS container"

Tell me if there is anything else I can do to help you on the way.

**Comment by sgan81** [comment] 2019-03-09 22:29
You could do a
```
dd if=/dev/sda2 of=sb.dat bs=4096 count=1
```
and then send me via mail or attach here the sb.dat file for analysis.

**Comment by V0oDoo** [comment] 2019-03-09 23:16
[sb.zip](https://github.com/sgan81/apfs-fuse/files/2948924/sb.zip)

**Comment by V0oDoo** [comment] 2019-03-09 23:17
> 
> 
> You could do a
> 
> ```
> dd if=/dev/sda2 of=sb.dat bs=4096 count=1
> ```
> 
> and then send me via mail or attach here the sb.dat file for analysis.

ok! here it is!
[sb.zip](https://github.com/sgan81/apfs-fuse/files/2948926/sb.zip)

**Comment by sgan81** [comment] 2019-03-10 00:05
Thanks ...
And I'm sorry, but this appears to be a CoreStorage header, not an APFS superblock. Maybe you have the APFS container inside a CoreStorage volume?
Run `diskutil cs list` to check if you are still using CoreStorage.

**Comment by V0oDoo** [comment] 2019-03-10 09:54
Oh dude, I'm so sorry. It is a HFS system. Darn I feel so dumb, my friend told me that he had upgraded to Mojave but obviously he hadn't.

Thanks a lot for you help! and sorry again.

**Comment by sgan81** [comment] 2019-03-10 12:05
LOL, no worries ... we all have these moments ;)
Leaving this open, since @Banaanhangwagen might have a different problem ...

**Comment by Banaanhangwagen** [comment] 2019-03-11 12:42
Unfortunatly, when I execute `./apfsutil image.dmg`
it gives me the following error: `This doesn't seem to be an apfs volume (invalid superblock) Unable to open APFS container`

This is what the partition table looks like when I execute on a mac `sudo gpt -r show disk3`
```
      start       size  index  contents
          0          1         PMBR
          1          1         Pri GPT header
          2          4         Pri GPT table
          6      76800      1  GPT part - C12A7328-F81F-11D2-BA4B-00A0C93EC93B
      76806  122061321      2  GPT part - 7C3457EF-0000-11AA-AA11-00306543ECAC
  122138127          4         Sec GPT table
  122138131          1         Sec GPT header
```

Indeed, when I look up the starting offset of the APFS container (76806), the magic string of an APFS container `4e 58 53 42` is present at offset 0x20:

```
sudo dd if=/dev/disk3 bs=4096 skip=76806 count=1 | hexdump
1+0 records in
1+0 records out
4096 bytes transferred in 0.002225 secs (1840766 bytes/sec)
0000000 6e 14 a8 6a 9a f1 ef 6f 01 00 00 00 00 00 00 00
0000010 9d 9d 15 00 00 00 00 00 01 00 00 80 00 00 00 00
0000020 4e 58 53 42 00 10 00 00 09 82 46 07 00 00 00 00
0000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000040 02 00 00 00 00 00 00 00 a5 63 d1 55 3b a6 4c aa
0000050 ad 74 57 e9 41 2c 92 6e 40 27 07 00 00 00 00 00
0000060 9e 9d 15 00 00 00 00 00 18 01 00 00 34 6c 00 00
0000070 44 23 01 00 00 00 00 00 0c 8b 00 00 00 00 00 00
0000080 50 00 00 00 ca 3c 00 00 4e 00 00 00 02 00 00 00
0000090 c0 3c 00 00 0a 00 00 00 77 c6 00 00 00 00 00 00
00000a0 df 46 0d 00 00 00 00 00 01 04 00 00 00 00 00 00
00000b0 00 00 00 00 64 00 00 00 02 04 00 00 00 00 00 00
00000c0 06 04 00 00 00 00 00 00 08 04 00 00 00 00 00 00
00000d0 79 c6 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
00003d0 00 00 00 00 00 00 00 00 d7 99 e7 01 00 00 00 00
00003e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
00004f0 04 00 00 00 00 00 00 00 56 1e 29 01 00 00 00 00
0000500 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000510 01 d0 6d 00 00 00 00 00 01 00 00 00 00 00 00 00
0000520 01 00 04 00 08 00 00 00 00 00 00 00 00 00 00 00
0000530 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0001000
```

**Comment by sgan81** [comment] 2019-03-11 16:09
I think I might have a vague idea what the problem is ... but just to be sure, can you hex-dump the first 6 blocks of the disk for me? Like `sudo dd if=/dev/disk3 bs=4096 count=6 | hexdump`?

**Comment by Banaanhangwagen** [comment] 2019-03-12 08:38
See attached files. (did a xxd as a bonus ;) Let me know if you need something else.
[hexdump_6_blocks.txt](https://github.com/sgan81/apfs-fuse/files/2955806/hexdump_6_blocks.txt)
[xxd_6_blocks.txt](https://github.com/sgan81/apfs-fuse/files/2955804/xxd_6_blocks.txt)

**Comment by sgan81** [comment] 2019-03-12 18:26
Thank you. Yes, my suspicion / fear was correct. The sector size is obviously 4096 bytes, and the partition table is stored accordingly. So since my driver always assumes sector sizes of 512 bytes, things might go slightly wrong ...
I will fix that, but it might take a few hours ...

As a workaround, you could pass the offset of the partition manually to the driver (`-s 314597376`). However I have a bad feeling that encryption might also use block sizes of 4096 bytes.

If you get errors complaining about encryption / keybags, you can try changing the following places in the code:

Line 132 in ApfsLib/ApfsVolume.cpp to:
```c++
constexpr int encryption_block_size = 0x1000;
```

In ApfsLib/KeyMgmt.cpp, starting from line 808, there are three hardcoded values 0x200 in `KeyManager::DecryptBlocks`. Change these to 0x1000.

Let me know if this works ... and thanks for your help :)

**Comment by Banaanhangwagen** [comment] 2019-03-16 13:30
I changed the value(s) in `ApfsLib/ApfsVolume.cpp` and in `ApfsLib/KeyMgmt.cpp` to 0x1000

Now I get the following:
```
./apfs-fuse image.dmg /path/mountpoint -s 314597376
Initialization of KeyManager failed.
Volume Macintosh HD is encrypted.
Enter password:
```
Unfortunately, the correct password is not accepted and it quits.


(I can feel we are almost there! ;)

**Comment by sgan81** [comment] 2019-03-16 18:17
Did you try only using -s and not changing any code?

But at least the offset appears to be correct now :)

The fix is in progress, I was able to partially reproduce the problem.

**Comment by Banaanhangwagen** [comment] 2019-03-16 19:04
> 
> Did you try only using -s and not changing any code?

Good news! When using `./apfs-fuse`with the `-s`flag without changing the code, the encryption password is accepted and the partition mounts correctly!

The other tools, `apfs-dump` `apfs-dump-quick` and `apfsutil`, still need a little calibration.

Good job!

**Comment by sgan81** [comment] 2019-03-16 19:11
Ok, so I'm on the right path ...

The problem is only that the GPT partition code wasn't able to handle a block size of 4096 bytes, since the partition table layout is slightly different. I will push a fix for this in a few days. Until then, use -s ;)

Thanks a lot for your help :)

**Comment by sgan81** [comment] 2019-04-12 16:52
There is now a blksize=N option, which should fix your problem. In your case, using `-o blksize=4096` should make you happy. :-)

**Comment by Banaanhangwagen** [comment] 2019-04-12 20:33
Cool. Will check it out. Give me a couple days.

**Comment by Banaanhangwagen** [comment] 2019-04-19 13:39
The `-o blksize=4096` works like a charm. 
Good job!

Will the other tools also be updated?

**Comment by sgan81** [comment] 2019-04-20 20:54
I have now added automatic detection of 4K blocksizes. The blksize parameter should not be needed anymore, except if the blocksize is neither 512 nor 4096 bytes.

**Comment by sgan81** [comment] 2019-04-20 20:59
@Banaanhangwagen regarding your reports for magnumripper, the 4K blocksize only caused problems with parsing the partition table (different layout), everything else works fine, independent of the physical block size.

**Closed** 2019-04-26 23:01 UTC
